### ISSUE TITLE
Implement `Drop` for mocks which executes `done()`

### ISSUE THREAD

**Issue by rnestler** [dbrgn/embedded-hal-mock#34]
When writing tests it's easy to forget a call to `done()` at the end to verify if there are any expectations left. By executing it in drop one can't forget it.

```rust
// will pass if no transaction happens 
#[test]
fn test() {
        let expectations = [
            Transaction::write(0x58, vec![0xab, 0xcd]),
        ];
        let mut mock = I2cMock::new(&expectations);
}
```

**Comment by dbrgn** [comment]
That would abort the entire test suite, not just the single test, right? Or do the tests run in a separate process?

**Comment by eldruin** [comment]
It would stop the whole thing. It is pretty hard core but missing calling `done` is probably bad enough, as the tests would do nothing otherwise. Furthermore, this is simply a programmer error, not something that starts failing due to some library code change, as opposed to a normal test value assert, for example.

**Comment by dbrgn** [comment]
Yeah, I guess that's fine, as long as it's clear *why* this happened :slightly_smiling_face: 

I assume there's no valid use case where `done` is intentionally not called, right? (At least none comes to my mind...)

**Comment by calebbourg** [comment]
Hello all,

I have a situation where a struct I've defined consumes an instance of the data bus struct.

Ex.
```rust
struct MyStruct<S> {
  spi: S // instance of spi 
}
```

`MyStruct` then has a number of methods that use the `spi` instance to communicate over the bus.

When testing using this crate I'm required to call `done` on the mocked instance of `spi`. I experience borrow after move compiler errors when attempting this due to `MyStruct`'s ownership over `spi`
Ex.
```rust
    let spi_expectations = vec![
        spi::Transaction::transfer(vec![0xe0], vec![0x0]),
        spi::Transaction::transfer(vec![0x37], vec![0x0]),
        spi::Transaction::transfer(vec![0x0], vec![0x0]),
        spi::Transaction::transfer(vec![0xee], vec![0x0]),
        spi::Transaction::transfer(vec![0xff], vec![0xef]),
    ];
    let spi = spi::Mock::new(&spi_expectations);

    let my_struct = MyStruct { spi : spi }; // move spi 

    my_struct.do_something();

    // ... make assertions

    spi.done() // borrow after move
```

I've added a method to `MyStruct` which produces a `&mut spi` which I can then call `done` on.

Ex.
```rust
    let spi_expectations = vec![
        spi::Transaction::transfer(vec![0xe0], vec![0x0]),
        spi::Transaction::transfer(vec![0x37], vec![0x0]),
        spi::Transaction::transfer(vec![0x0], vec![0x0]),
        spi::Transaction::transfer(vec![0xee], vec![0x0]),
        spi::Transaction::transfer(vec![0xff], vec![0xef]),
    ];
    let mut spi = spi::Mock::new(&spi_expectations);

    let my_struct = MyStruct { spi : spi };

    my_struct.do_something();

    // ... make assertions

   let mut spi = my_struct.spi_as_mut_ref(); // &mut spi

   spi.done()
```
 
This is fine although I would rather the design `MyStruct`'s public interface not be informed by needing a method specific to tests.

Curious on thoughts here around modifying this crate's API to allow for me not needing to call `done` in this fashion. Or is this intentional and I should consider re-thinking my own design?

Any help very much appreciated!

**Comment by dbrgn** [comment]
Often drivers provide a way to destroy the driver instance and return the data bus (e.g. `destroy` at https://docs.rs/veml7700/0.1.7/veml7700/struct.Veml7700.html#method.destroy). I think that would be the best way for your `MyStruct` as well: A `destroy` method that returns the mocked SPI bus.

**Comment by calebbourg** [comment]
Ah I see. I will go with that approach. Thank you very much!

**Comment by rnestler** [comment]
@dbrgn Is this implemented now? I can't find any reference to that.

**Comment by dbrgn** [comment]
@rnestler oops, sorry, I closed this by accident!

**Comment by dbrgn** [comment]
An error message can get around the Cargo output capturing by writing directly to `std::io::Write`. However, there's an issue if an assertion in a test actually fails, e.g.

```rust
#[test]
fn do_some_testing() {
    let mut mock = SomeMock::new();
    assert_eq(1, 2);
    mock.done();
}
```

In that case the code panicks, which causes unwinding, and thus calls `drop` on the mock before `done` was called. This results in an immediate abort ("panicking while panicking"):

![screenshot-20230107-012329](https://user-images.githubusercontent.com/105168/211121454-9519d87b-ebc7-4ef7-a017-9032666d1c35.png)

So: Is there a way to know if we're already unwinding, or not?

**Comment by dbrgn** [comment]
Ah, there's https://doc.rust-lang.org/std/thread/fn.panicking.html. However, the question is whether we actually need to abort, or whether the warning is sufficient. An abort would result in test failure (e.g. in CI), might be a good thing. OTOH a warning could be sufficient and would be less "destructive".

**Comment by dbrgn** [comment]
This is a good check, I already found a bug in `embedded-hal-mock` thanks to it 😂 (#58)

PR is here: #59. Because it adds potentially breaking changes (tests may fail), I'll release it in a new semver-breaking release.

**Comment by rnestler** [comment]
> OTOH a warning could be sufficient and would be less "destructive".

Might be enough, but I saw you did both?
