### ISSUE TITLE
Feature Request: IoPin mocks

### ISSUE THREAD

**Issue by rhempel** [dbrgn/embedded-hal-mock#51]
I'm just getting started with Embedded Rust (40 years of embedded C though) and find the best way is to dig in to a relevant project and see what happens.

For something I'm working on, I need the IoPin functionality and I also want to do it "right" using TDD from the start. This is something I am passionate about for the last 5 years :-)

I'll try and build the mocks for the IoPin functionality and issue a pull request - but I have opened this feature request just in case you already have it ready to go and want some testers :-)

**Comment by rursprung** [comment]
just FYI: in embedded-hal 1.0 `IoPin` has been removed and it's unclear if it'll be added again. see the discussion in https://github.com/rust-embedded/embedded-hal/issues/340

but i guess that wouldn't prevent @dbrgn from accepting a PR adding the mock for 0.x; this is more for your information depending on what you plan on building.

**Comment by dbrgn** [comment]
> but i guess that wouldn't prevent @dbrgn from accepting a PR adding the mock for 0.x; this is more for your information depending on what you plan on building.

Correct 🙂

**Comment by dbrgn** [comment]
I'll close this for now, since - as discussed above - the `IoPin` trait was removed from embedded-hal 1.

Regarding my statement in the comment above: Since embedded-hal 1 is now stable, I would only reluctantly accept a PR for embedded-hal 0.x, and only if it were very simple to review. I think it makes more sense to treat embedded-hal 0.x support as deprecated, and focus on 1.x instead.
